// Generated by CIRCT firtool-1.62.0
module HelloExt(	// src/main/scala/com/helloworld/helloworld_ext.scala:7:7
  input        clock,	// src/main/scala/com/helloworld/helloworld_ext.scala:7:7
               reset,	// src/main/scala/com/helloworld/helloworld_ext.scala:7:7
  input  [1:0] io_sw,	// src/main/scala/com/helloworld/helloworld_ext.scala:8:14
  output       io_led	// src/main/scala/com/helloworld/helloworld_ext.scala:8:14
);

  assign io_led = io_sw[0];	// src/main/scala/com/helloworld/helloworld_ext.scala:7:7, :12:18
endmodule

